### ISSUE TITLE
ansible jinja2 template with more than one secret crashes

### ISSUE THREAD

**Issue by darkobas2** [bitwarden/sdk#985]
### Steps To Reproduce

ansible jinja2 template with with more than one secrets to fill 

### Expected Result

it should not be limited to one item

### Actual Result

thread '<unnamed>' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-log-0.9.0/src/lib.rs:570:16:
called `Result::unwrap()` on an `Err` value: SetLoggerError(())
stack backtrace:
   0:     0x7f9464cf929e - std::backtrace_rs::backtrace::libunwind::trace::ha637c64ce894333a
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7f9464cf929e - std::backtrace_rs::backtrace::trace_unsynchronized::h47f62dea28e0c88d
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f9464cf929e - std::sys_common::backtrace::_print_fmt::h9eef0abe20ede486
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f9464cf929e - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hed7f999df88cc644
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f9464b12fc0 - core::fmt::rt::Argument::fmt::h1539a9308b8d058d
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/rt.rs:142:9
   5:     0x7f9464b12fc0 - core::fmt::write::h3a39390d8560d9c9
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/mod.rs:1120:17
   6:     0x7f9464cf6d83 - std::io::Write::write_fmt::h5fc9997dfe05f882
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/io/mod.rs:1762:15
   7:     0x7f9464cf9044 - std::sys_common::backtrace::_print::h894006fb5c6f3d45
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f9464cf9044 - std::sys_common::backtrace::print::h23a2d212c6fff936
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f9464cfa730 - std::panicking::default_hook::{{closure}}::h8a1d2ee00185001a
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:272:22
  10:     0x7f9464cfa44f - std::panicking::default_hook::h6038f2eba384e475
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:292:9
  11:     0x7f9464cfac58 - std::panicking::rust_panic_with_hook::h2b5517d590cab22e
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:779:13
  12:     0x7f9464cfab3e - std::panicking::begin_panic_handler::{{closure}}::h233112c06e0ef43e
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:657:13
  13:     0x7f9464cf9766 - std::sys_common::backtrace::__rust_end_short_backtrace::h6e893f24d7ebbff8
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x7f9464cfa8c2 - rust_begin_unwind
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
  15:     0x7f9464a4df15 - core::panicking::panic_fmt::hbf0e066aabfa482c
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
  16:     0x7f9464a4e453 - core::result::unwrap_failed::hddb4fea594200c52
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1653:5
  17:     0x7f9464b03e01 - bitwarden_py::client::_::<impl pyo3::impl_::pyclass::PyMethods<bitwarden_py::client::BitwardenClient> for pyo3::impl_::pyclass::PyClassImplCollector<bitwarden_py::client::BitwardenClient>>::py_methods::ITEMS::trampoline::hcd729d612dc933fd
  18:     0x7f9469bb3059 - <unknown>
  19:     0x7f9469bb2edf - _PyObject_MakeTpCall
  20:     0x7f9469bbb438 - _PyEval_EvalFrameDefault
  21:     0x7f9469bb786a - <unknown>
  22:     0x7f9469bb5c0b - _PyObject_FastCallDictTstate
  23:     0x7f9469bdda6f - <unknown>
  24:     0x7f9469bb30f3 - <unknown>
  25:     0x7f9469bb2edf - _PyObject_MakeTpCall
  26:     0x7f9469bbb438 - _PyEval_EvalFrameDefault
  27:     0x7f9469bb786a - <unknown>
  28:     0x7f9469bee7dc - <unknown>
  29:     0x7f9469bdf259 - <unknown>
  30:     0x7f9469bbf7c0 - _PyEval_EvalFrameDefault
  31:     0x7f9469bb786a - <unknown>
  32:     0x7f9469bee7dc - <unknown>
  33:     0x7f9469bdf259 - <unknown>
  34:     0x7f9469bbf7c0 - _PyEval_EvalFrameDefault
  35:     0x7f9469bb786a - <unknown>
  36:     0x7f9469bee7dc - <unknown>
  37:     0x7f9469bdf259 - <unknown>
  38:     0x7f9469bbf7c0 - _PyEval_EvalFrameDefault
  39:     0x7f9469bed57a - <unknown>
  40:     0x7f9469bed404 - <unknown>
  41:     0x7f9469c28c29 - <unknown>
  42:     0x7f9469bec0fd - <unknown>
  43:     0x7f9469c0a67b - <unknown>
  44:     0x7f9469bc73e3 - PyObject_Vectorcall
  45:     0x7f9469bbb438 - _PyEval_EvalFrameDefault
  46:     0x7f9469bb786a - <unknown>
  47:     0x7f9469c07198 - <unknown>
  48:     0x7f9469c070b8 - <unknown>
  49:     0x7f9469bbbcfc - _PyEval_EvalFrameDefault
  50:     0x7f9469bed57a - <unknown>
  51:     0x7f9469bed404 - <unknown>
  52:     0x7f9469c28c29 - <unknown>
  53:     0x7f9469bec0fd - <unknown>
  54:     0x7f9469c0a67b - <unknown>
  55:     0x7f9469bc73e3 - PyObject_Vectorcall
  56:     0x7f9469bbb438 - _PyEval_EvalFrameDefault
  57:     0x7f9469bb786a - <unknown>
  58:     0x7f9469bb5c0b - _PyObject_FastCallDictTstate
  59:     0x7f9469bdda6f - <unknown>
  60:     0x7f9469bb30f3 - <unknown>
  61:     0x7f9469bb2edf - _PyObject_MakeTpCall
  62:     0x7f9469bbb438 - _PyEval_EvalFrameDefault
  63:     0x7f9469bb786a - <unknown>
  64:     0x7f9469c3ab4f - PyEval_EvalCode
  65:     0x7f9469c57cb3 - <unknown>
  66:     0x7f9469c5420a - <unknown>
  67:     0x7f9469c6a452 - <unknown>
  68:     0x7f9469c69c34 - _PyRun_SimpleFileObject
  69:     0x7f9469c698e4 - _PyRun_AnyFileObject
  70:     0x7f9469c630e4 - Py_RunMain
  71:     0x7f9469c2ade7 - Py_BytesMain
  72:     0x7f946962a340 - __libc_start_call_main
  73:     0x7f946962a409 - __libc_start_main@@GLIBC_2.34
  74:     0x556673774075 - _start
  75:                0x0 - <unknown>
ERROR! A worker was found in a dead state

### Operating System

Linux

### Build Version

0.5.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by dani-garcia** [comment]
This is the same issue reported here: https://github.com/bitwarden/sdk/issues/697, which was fixed by https://github.com/bitwarden/sdk/pull/676

The fix should be included in the next release, but for the moment there are some workarounds mentioned in the PR: https://github.com/bitwarden/sdk/pull/676#issuecomment-2267574549

**Comment by darkobas2** [comment]
> This is the same issue reported here: #697, which was fixed by #676
> 
> The fix should be included in the next release, but for the moment there are some workarounds mentioned in the PR: [#676 (comment)](https://github.com/bitwarden/sdk/pull/676#issuecomment-2267574549)

well i did read that before and i still have the issue... I did try to build from the latest source.. it gave me bitwarden_sdk-0.1.0-cp311-cp311-manylinux_2_28_x86_64.whl which I installed and you see trace above.... maybe I didnt do it correct.
what baffled me also is that that patch was merged in begining of April and the 0.5.0 was released april 29th... So i was wondering if it was the fix that it should be already included in the release
